<?php
namespace MailPoetVendor;
if (!defined('ABSPATH')) exit;
// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInit6d2a499f6988145dbf867389d4b230f9::getLoader();
